'pm10'
No pollutant named pm10
Internal Server Error: /vzduch
Traceback (most recent call last):
  File "C:\Users\tomas\AppData\Roaming\Python\Python39\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\tomas\AppData\Roaming\Python\Python39\site-packages\django\core\handlers\base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\tomas\AppData\Roaming\Python\Python39\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\tomas\AppData\Roaming\Python\Python39\site-packages\django\views\generic\base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "D:\git\vzduch\airMonitor\views\VzduchView.py", line 14, in get
    wind = Wind()
  File "D:\git\vzduch\airMonitor\models\Wind.py", line 7, in __init__
    self.air_path = settings.GUST_PATH
  File "C:\Users\tomas\AppData\Roaming\Python\Python39\site-packages\django\conf\__init__.py", line 84, in __getattr__
    val = getattr(self._wrapped, name)
AttributeError: 'Settings' object has no attribute 'GUST_PATH'
"GET /vzduch HTTP/1.1" 500 81782
Internal Server Error: /vzduch
Traceback (most recent call last):
  File "C:\Users\tomas\AppData\Roaming\Python\Python39\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\tomas\AppData\Roaming\Python\Python39\site-packages\django\core\handlers\base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\tomas\AppData\Roaming\Python\Python39\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\tomas\AppData\Roaming\Python\Python39\site-packages\django\views\generic\base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "D:\git\vzduch\airMonitor\views\VzduchView.py", line 15, in get
    wind_data = wind.load_data()
  File "D:\git\vzduch\airMonitor\models\Wind.py", line 11, in load_data
    date_dirs = [file for file in os.listdir(self.air_path)].sort(reverse=True)[-7:]
TypeError: 'NoneType' object is not subscriptable
"GET /vzduch HTTP/1.1" 500 77952
Internal Server Error: /vzduch
Traceback (most recent call last):
  File "C:\Users\tomas\AppData\Roaming\Python\Python39\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\tomas\AppData\Roaming\Python\Python39\site-packages\django\core\handlers\base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\tomas\AppData\Roaming\Python\Python39\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\tomas\AppData\Roaming\Python\Python39\site-packages\django\views\generic\base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "D:\git\vzduch\airMonitor\views\VzduchView.py", line 15, in get
    wind_data = wind.load_data()
  File "D:\git\vzduch\airMonitor\models\Wind.py", line 12, in load_data
    print(date_dirs[-7:])
TypeError: 'NoneType' object is not subscriptable
"GET /vzduch HTTP/1.1" 500 77938
Internal Server Error: /vzduch
Traceback (most recent call last):
  File "C:\Users\tomas\AppData\Roaming\Python\Python39\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\tomas\AppData\Roaming\Python\Python39\site-packages\django\core\handlers\base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\tomas\AppData\Roaming\Python\Python39\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\tomas\AppData\Roaming\Python\Python39\site-packages\django\views\generic\base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "D:\git\vzduch\airMonitor\views\VzduchView.py", line 15, in get
    wind_data = wind.load_data()
  File "D:\git\vzduch\airMonitor\models\Wind.py", line 24, in load_data
    for picture in os.listdir(self.air_path + '/' + date_directory + '/' + picture_type):
TypeError: unsupported operand type(s) for +: 'WindowsPath' and 'str'
"GET /vzduch HTTP/1.1" 500 79792
Internal Server Error: /vzduch
Traceback (most recent call last):
  File "C:\Users\tomas\AppData\Roaming\Python\Python39\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\tomas\AppData\Roaming\Python\Python39\site-packages\django\core\handlers\base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\tomas\AppData\Roaming\Python\Python39\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\tomas\AppData\Roaming\Python\Python39\site-packages\django\views\generic\base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "D:\git\vzduch\airMonitor\views\VzduchView.py", line 15, in get
    wind_data = wind.load_data()
  File "D:\git\vzduch\airMonitor\models\Wind.py", line 24, in load_data
    picture_path = self.air_path + '/' + date_directory + '/' + picture_type
TypeError: unsupported operand type(s) for +: 'WindowsPath' and 'str'
"GET /vzduch HTTP/1.1" 500 79938
Internal Server Error: /vzduch
Traceback (most recent call last):
  File "C:\Users\tomas\AppData\Roaming\Python\Python39\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\tomas\AppData\Roaming\Python\Python39\site-packages\django\core\handlers\base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\tomas\AppData\Roaming\Python\Python39\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\tomas\AppData\Roaming\Python\Python39\site-packages\django\views\generic\base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "D:\git\vzduch\airMonitor\views\VzduchView.py", line 15, in get
    wind_data = wind.load_data()
  File "D:\git\vzduch\airMonitor\models\Wind.py", line 25, in load_data
    picture_path = self.air_path + '/' + date_directory + '/' + picture_type
TypeError: unsupported operand type(s) for +: 'WindowsPath' and 'str'
"GET /vzduch HTTP/1.1" 500 79996
Internal Server Error: /vzduch
Traceback (most recent call last):
  File "C:\Users\tomas\AppData\Roaming\Python\Python39\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\tomas\AppData\Roaming\Python\Python39\site-packages\django\core\handlers\base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\tomas\AppData\Roaming\Python\Python39\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\tomas\AppData\Roaming\Python\Python39\site-packages\django\views\generic\base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "D:\git\vzduch\airMonitor\views\VzduchView.py", line 15, in get
    wind_data = wind.load_data()
  File "D:\git\vzduch\airMonitor\models\Wind.py", line 25, in load_data
    for picture in os.listdir(picture_path):
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'D:\\git\\vzduch\\airMonitor\\static\\air\\2020-11-16_00\\GUST'
"GET /vzduch HTTP/1.1" 500 80260
Internal Server Error: /vzduch
Traceback (most recent call last):
  File "C:\Users\tomas\AppData\Roaming\Python\Python39\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\tomas\AppData\Roaming\Python\Python39\site-packages\django\core\handlers\base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\tomas\AppData\Roaming\Python\Python39\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\tomas\AppData\Roaming\Python\Python39\site-packages\django\views\generic\base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "D:\git\vzduch\airMonitor\views\VzduchView.py", line 17, in get
    return render(request, "windFinal.html", {
  File "C:\Users\tomas\AppData\Roaming\Python\Python39\site-packages\django\shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\tomas\AppData\Roaming\Python\Python39\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "C:\Users\tomas\AppData\Roaming\Python\Python39\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "C:\Users\tomas\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 170, in render
    return self._render(context)
  File "C:\Users\tomas\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 162, in _render
    return self.nodelist.render(context)
  File "C:\Users\tomas\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
  File "C:\Users\tomas\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "C:\Users\tomas\AppData\Roaming\Python\Python39\site-packages\django\template\loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "C:\Users\tomas\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 162, in _render
    return self.nodelist.render(context)
  File "C:\Users\tomas\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
  File "C:\Users\tomas\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "C:\Users\tomas\AppData\Roaming\Python\Python39\site-packages\django\template\loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "C:\Users\tomas\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 162, in _render
    return self.nodelist.render(context)
  File "C:\Users\tomas\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
  File "C:\Users\tomas\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "C:\Users\tomas\AppData\Roaming\Python\Python39\site-packages\django\template\loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "C:\Users\tomas\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
  File "C:\Users\tomas\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "C:\Users\tomas\AppData\Roaming\Python\Python39\site-packages\django\template\loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "C:\Users\tomas\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
  File "C:\Users\tomas\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "C:\Users\tomas\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 988, in render
    output = self.filter_expression.resolve(context)
  File "C:\Users\tomas\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 698, in resolve
    new_obj = func(obj, *arg_vals)
  File "C:\Users\tomas\AppData\Roaming\Python\Python39\site-packages\django\template\defaultfilters.py", line 91, in json_script
    return _json_script(value, element_id)
  File "C:\Users\tomas\AppData\Roaming\Python\Python39\site-packages\django\utils\html.py", line 85, in json_script
    json_str = json.dumps(value, cls=DjangoJSONEncoder).translate(_json_script_escapes)
  File "C:\Program Files\Python39\lib\json\__init__.py", line 234, in dumps
    return cls(
  File "C:\Program Files\Python39\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Program Files\Python39\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
TypeError: keys must be str, int, float, bool or None, not datetime.date
"GET /vzduch HTTP/1.1" 500 367028
Internal Server Error: /vzduch
Traceback (most recent call last):
  File "C:\Users\tomas\AppData\Roaming\Python\Python39\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\tomas\AppData\Roaming\Python\Python39\site-packages\django\core\handlers\base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\tomas\AppData\Roaming\Python\Python39\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\tomas\AppData\Roaming\Python\Python39\site-packages\django\views\generic\base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "D:\git\vzduch\airMonitor\views\VzduchView.py", line 17, in get
    return render(request, "windFinal.html", {
  File "C:\Users\tomas\AppData\Roaming\Python\Python39\site-packages\django\shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\tomas\AppData\Roaming\Python\Python39\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "C:\Users\tomas\AppData\Roaming\Python\Python39\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "C:\Users\tomas\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 170, in render
    return self._render(context)
  File "C:\Users\tomas\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 162, in _render
    return self.nodelist.render(context)
  File "C:\Users\tomas\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
  File "C:\Users\tomas\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "C:\Users\tomas\AppData\Roaming\Python\Python39\site-packages\django\template\loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "C:\Users\tomas\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 162, in _render
    return self.nodelist.render(context)
  File "C:\Users\tomas\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
  File "C:\Users\tomas\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "C:\Users\tomas\AppData\Roaming\Python\Python39\site-packages\django\template\loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "C:\Users\tomas\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 162, in _render
    return self.nodelist.render(context)
  File "C:\Users\tomas\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
  File "C:\Users\tomas\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "C:\Users\tomas\AppData\Roaming\Python\Python39\site-packages\django\template\loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "C:\Users\tomas\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
  File "C:\Users\tomas\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "C:\Users\tomas\AppData\Roaming\Python\Python39\site-packages\django\template\loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "C:\Users\tomas\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
  File "C:\Users\tomas\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "C:\Users\tomas\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 988, in render
    output = self.filter_expression.resolve(context)
  File "C:\Users\tomas\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 698, in resolve
    new_obj = func(obj, *arg_vals)
  File "C:\Users\tomas\AppData\Roaming\Python\Python39\site-packages\django\template\defaultfilters.py", line 91, in json_script
    return _json_script(value, element_id)
  File "C:\Users\tomas\AppData\Roaming\Python\Python39\site-packages\django\utils\html.py", line 85, in json_script
    json_str = json.dumps(value, cls=DjangoJSONEncoder).translate(_json_script_escapes)
  File "C:\Program Files\Python39\lib\json\__init__.py", line 234, in dumps
    return cls(
  File "C:\Program Files\Python39\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Program Files\Python39\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "C:\Users\tomas\AppData\Roaming\Python\Python39\site-packages\django\core\serializers\json.py", line 105, in default
    return super().default(o)
  File "C:\Program Files\Python39\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type WindowsPath is not JSON serializable
"GET /vzduch HTTP/1.1" 500 375845
Internal Server Error: /vzduch
Traceback (most recent call last):
  File "C:\Users\tomas\AppData\Roaming\Python\Python39\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\tomas\AppData\Roaming\Python\Python39\site-packages\django\core\handlers\base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\tomas\AppData\Roaming\Python\Python39\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\tomas\AppData\Roaming\Python\Python39\site-packages\django\views\generic\base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "D:\git\vzduch\airMonitor\views\VzduchView.py", line 15, in get
    wind_data = wind.load_data()
  File "D:\git\vzduch\airMonitor\models\Wind.py", line 28, in load_data
    wind_data[key_date][picture_type].append(picture)
KeyError: '16.11.2020'
"GET /vzduch HTTP/1.1" 500 79815
Internal Server Error: /vzduch
Traceback (most recent call last):
  File "C:\Users\tomas\AppData\Roaming\Python\Python39\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\tomas\AppData\Roaming\Python\Python39\site-packages\django\core\handlers\base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\tomas\AppData\Roaming\Python\Python39\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\tomas\AppData\Roaming\Python\Python39\site-packages\django\views\generic\base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "D:\git\vzduch\airMonitor\views\VzduchView.py", line 15, in get
    wind_data = wind.load_data()
  File "D:\git\vzduch\airMonitor\models\Wind.py", line 28, in load_data
    wind_data[key_date][picture_type].append(picture)
KeyError: '16.11.2020'
"GET /vzduch HTTP/1.1" 500 79815
Internal Server Error: /vzduch
Traceback (most recent call last):
  File "C:\Users\tomas\AppData\Roaming\Python\Python39\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\tomas\AppData\Roaming\Python\Python39\site-packages\django\core\handlers\base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\tomas\AppData\Roaming\Python\Python39\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\tomas\AppData\Roaming\Python\Python39\site-packages\django\views\generic\base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "D:\git\vzduch\airMonitor\views\VzduchView.py", line 15, in get
    wind_data = wind.load_data()
  File "D:\git\vzduch\airMonitor\models\Wind.py", line 28, in load_data
    wind_data['PICTURES'][key_date][picture_type].append(picture)
KeyError: '16.11.2020'
"GET /vzduch HTTP/1.1" 500 79859
Internal Server Error: /vzduch
Traceback (most recent call last):
  File "C:\Users\tomas\AppData\Roaming\Python\Python39\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\tomas\AppData\Roaming\Python\Python39\site-packages\django\core\handlers\base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\tomas\AppData\Roaming\Python\Python39\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\tomas\AppData\Roaming\Python\Python39\site-packages\django\views\generic\base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "D:\git\vzduch\airMonitor\views\VzduchView.py", line 17, in get
    return render(request, "windFinal.html", {
  File "C:\Users\tomas\AppData\Roaming\Python\Python39\site-packages\django\shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\tomas\AppData\Roaming\Python\Python39\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "C:\Users\tomas\AppData\Roaming\Python\Python39\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "C:\Users\tomas\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 170, in render
    return self._render(context)
  File "C:\Users\tomas\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 162, in _render
    return self.nodelist.render(context)
  File "C:\Users\tomas\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
  File "C:\Users\tomas\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "C:\Users\tomas\AppData\Roaming\Python\Python39\site-packages\django\template\loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "C:\Users\tomas\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 162, in _render
    return self.nodelist.render(context)
  File "C:\Users\tomas\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
  File "C:\Users\tomas\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "C:\Users\tomas\AppData\Roaming\Python\Python39\site-packages\django\template\loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "C:\Users\tomas\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 162, in _render
    return self.nodelist.render(context)
  File "C:\Users\tomas\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
  File "C:\Users\tomas\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "C:\Users\tomas\AppData\Roaming\Python\Python39\site-packages\django\template\loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "C:\Users\tomas\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
  File "C:\Users\tomas\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "C:\Users\tomas\AppData\Roaming\Python\Python39\site-packages\django\template\loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "C:\Users\tomas\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
  File "C:\Users\tomas\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "C:\Users\tomas\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 988, in render
    output = self.filter_expression.resolve(context)
  File "C:\Users\tomas\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 698, in resolve
    new_obj = func(obj, *arg_vals)
  File "C:\Users\tomas\AppData\Roaming\Python\Python39\site-packages\django\template\defaultfilters.py", line 91, in json_script
    return _json_script(value, element_id)
  File "C:\Users\tomas\AppData\Roaming\Python\Python39\site-packages\django\utils\html.py", line 85, in json_script
    json_str = json.dumps(value, cls=DjangoJSONEncoder).translate(_json_script_escapes)
  File "C:\Program Files\Python39\lib\json\__init__.py", line 234, in dumps
    return cls(
  File "C:\Program Files\Python39\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Program Files\Python39\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "C:\Users\tomas\AppData\Roaming\Python\Python39\site-packages\django\core\serializers\json.py", line 105, in default
    return super().default(o)
  File "C:\Program Files\Python39\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type WindowsPath is not JSON serializable
"GET /vzduch HTTP/1.1" 500 377499
'pm10'
No pollutant named pm10
'pm10'
No pollutant named pm10
'pm10'
No pollutant named pm10
'pm10'
No pollutant named pm10
'pm10'
No pollutant named pm10
'pm10'
No pollutant named pm10
Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\tomas\AppData\Roaming\Python\Python39\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\tomas\AppData\Roaming\Python\Python39\site-packages\django\db\backends\sqlite3\base.py", line 413, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.OperationalError: no such table: si

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\tomas\AppData\Roaming\Python\Python39\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\tomas\AppData\Roaming\Python\Python39\site-packages\django\core\handlers\base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\tomas\AppData\Roaming\Python\Python39\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\tomas\AppData\Roaming\Python\Python39\site-packages\django\views\generic\base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "D:\git\vzduch\airMonitor\views\HomeView.py", line 37, in get
    stations_table = StationsTable().load_data(date)
  File "D:\git\vzduch\airMonitor\models\StationsTable.py", line 222, in load_data
    table_data = self._create_table_data(self._get_stations_with_values())
  File "D:\git\vzduch\airMonitor\models\StationsTable.py", line 183, in _get_stations_with_values
    stations = self._get_stations()
  File "D:\git\vzduch\airMonitor\models\StationsTable.py", line 101, in _get_stations
    stations_raw = [(s.get_station().id, s.get_station().name) for s in Station.all()]
  File "D:\git\vzduch\airMonitor\models\Station.py", line 13, in all
    for station in Si.objects.filter(ci=78).filter(~Q(lat=0.0)):
  File "C:\Users\tomas\AppData\Roaming\Python\Python39\site-packages\django\db\models\query.py", line 287, in __iter__
    self._fetch_all()
  File "C:\Users\tomas\AppData\Roaming\Python\Python39\site-packages\django\db\models\query.py", line 1308, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "C:\Users\tomas\AppData\Roaming\Python\Python39\site-packages\django\db\models\query.py", line 53, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "C:\Users\tomas\AppData\Roaming\Python\Python39\site-packages\django\db\models\sql\compiler.py", line 1156, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\tomas\AppData\Roaming\Python\Python39\site-packages\django\db\backends\utils.py", line 98, in execute
    return super().execute(sql, params)
  File "C:\Users\tomas\AppData\Roaming\Python\Python39\site-packages\django\db\backends\utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "C:\Users\tomas\AppData\Roaming\Python\Python39\site-packages\django\db\backends\utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\tomas\AppData\Roaming\Python\Python39\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\tomas\AppData\Roaming\Python\Python39\site-packages\django\db\utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\tomas\AppData\Roaming\Python\Python39\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\tomas\AppData\Roaming\Python\Python39\site-packages\django\db\backends\sqlite3\base.py", line 413, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.OperationalError: no such table: si
"GET / HTTP/1.1" 500 153075
